import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
	weight: ['400', '500', '700'],
	subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className="h-full">
			<body
				className={classNames(
					roboto.className,
					'min-h-screen w-screen bg-mydarkgrey'
				)}>
				{children}
			</body>
		</html>
	)
}
